package com.liveness.detection

data class LivenessConfig(
  val readyMs: Long = 1800L,
  val sessionTimeoutMs: Long = 120000L,
  val baselineFrames: Int = 8,
  val yawTurnDelta: Float = 9f,
  val yawWrongDirDelta: Float = 16f,
  val headTurnHoldMs: Long = 80L,
  val nodDownDelta: Float = 3f,
  val nodReturnFraction: Float = 0.85f,
  val nodReturnMaxDelta: Float = 12f,
  val blinkClosedThreshold: Float = 0.30f,
  val blinkOpenThreshold: Float = 0.25f,
  val earClosedThreshold: Float = 0.20f,
  val earOpenThreshold: Float = 0.25f,
  val blinkMaxDurationMs: Long = 4000L,
  val mouthOpenThreshold: Float = 0.20f,
  val mouthOpenMarThreshold: Float = 0.20f,
  val mouthHoldMs: Long = 50L,
  val maxYawDuringBlink: Float = 30f,
  val maxPitchDuringBlink: Float = 30f,
  val maxYawDuringNod: Float = 40f,
  val maxYawDuringMouth: Float = 35f,
  val maxPitchDuringMouth: Float = 35f,
  val ovalCx: Float = 0.50f,
  val ovalCy: Float = 0.42f,
  val ovalRx: Float = 0.32f,
  val ovalRy: Float = 0.40f,
  val minFaceSize: Float = 0.10f,
  val maxFaceSize: Float = 0.62f,
  val captureDelayMs: Long = 700L,
  val captureMaxAttempts: Int = 90,
  val captureMaxYaw: Float = 18f,
  val captureMaxPitch: Float = 18f,
  val captureMaxMouthScore: Float = 0.20f,
  val captureMaxBlinkScore: Float = 0.25f,
  val captureMinEar: Float = 0.22f,
  val captureMaxMar: Float = 0.22f,
  val shuffleSteps: Boolean = true,
  val faceDetectionConfidence: Float = 0.5f,
  val facePresenceConfidence: Float = 0.5f,
  val faceTrackingConfidence: Float = 0.5f,
  val cdnMaxRetries: Int = 5,
  val cdnAttemptTimeoutMs: Long = 45000L,
  val connectivityCheckTimeoutMs: Long = 5000L,
)
