const fs = require("fs");
const path = require("path");

const audiosDir = path.join(__dirname, "..", "public", "audios");
const outFile = path.join(__dirname, "..", "src", "default-sounds.generated.ts");

const KEYS = ["left", "blink", "right", "nod", "mouth", "good", "capture"];

if (!fs.existsSync(audiosDir)) {
  console.warn("web-sdk: public/audios not found, skipping embed");
  fs.writeFileSync(
    outFile,
    "// No audio files found at build time. Pass sounds in options to enable.\nexport const DEFAULT_SOUND_DATA_URLS: Record<string, string> = {};\n"
  );
  process.exit(0);
}

const data = {};
for (const key of KEYS) {
  const f = path.join(audiosDir, key + ".mp3");
  if (fs.existsSync(f)) {
    const buf = fs.readFileSync(f);
    data[key] = "data:audio/mpeg;base64," + buf.toString("base64");
  }
}

const lines = [
  "// Generated by scripts/embed-audios.cjs – do not edit",
  "export const DEFAULT_SOUND_DATA_URLS: Record<string, string> = " +
    JSON.stringify(data, null, 2) +
    ";",
];
fs.writeFileSync(outFile, lines.join("\n"));
console.log("web-sdk: embedded", Object.keys(data).length, "audio(s) into default-sounds.generated.ts");
